### ISSUE TITLE
error[E0635]: unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by cacilhas** [dtolnay/proc-macro2#398]
```
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> $HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |
```

Stopped working in nightly 0.72.

**Comment by dtolnay** [comment]
This was already fixed as of 4 weeks ago (1.0.60+).

**Comment by chorman0773** [comment]
I had this break in a transitive dep (am not using the cfg). I hope that updating bytemuck, and thus bytemuck_derive deps on a fixed version of proc-macro2. It may be a good idea to look into how features in general are detected if it's using feature detection to avoid such breakage in the future.
