### PR TITLE
Make .start() and .end() work on Rust 1.88.

### PR DESCRIPTION
**Pull request by VictorArcium**
A lot of `proc_macro2::Span` methods have been stabilized in Rust 1.88: https://doc.rust-lang.org/stable/proc_macro/struct.Span.html#method.line.

This PR does the minimal change to make `.start()` and `.end()` work using these new methods.

### CODE REVIEW

**Comment by VictorArcium** [comment]
Does not work. I will reopen after I fix.

**Review by dtolnay — CHANGES_REQUESTED** [review]
This implementation is going to cause build failures for projects that use `allow-features=`.

```console
$ RUSTFLAGS=-Zallow-features= cargo +nightly-2025-04-26 check --features=span-locations

error[E0658]: use of unstable library feature `proc_macro_span`
   --> src/wrapper.rs:436:25
    |
436 |                 line: s.line(),
    |                         ^^^^
    |
    = note: see issue #54725 <https://github.com/rust-lang/rust/issues/54725> for more information
    = help: add `#![feature(proc_macro_span)]` to the crate attributes to enable
    = note: this compiler was built on 2025-04-25; consider upgrading it if it is out of date
```

I put up a safer alternative in #517. Thanks anyway for the PR!
